### ISSUE TITLE
AE Data for J&K, Goa_Daman_&_Diu is not visible in GitList

### ISSUE THREAD

**Issue by nissabasim** [tcpd/tcpd-data#12]
Oops! fatal: Not a valid object name master:AE/Data/Goa_Daman_\&_Diu/

**Comment by sudesh-ashoka** [comment]
The problem seems to be for States which have ampersand '&' in the directory.

**Comment by sudesh-ashoka** [comment]
This is a known issue in gitlist. An implicit escaper is added to special characters.
Had to modify Controller php files to make this work.
The following line had to be commented.
->convert('Path', 'escaper.argument:escape')

Fixed Now. 
@nissabasim please test and close this.

**Comment by nissabasim** [comment]
Tested.
