### ISSUE TITLE
Karnataka Electoral Subregions update (ECO)

### ISSUE THREAD

**Issue by girishbs123** [tcpd/tcpd-data#25]
I have replaced the administrative divisions with electoral subregions, according to the nomenclature used by Prof Sandeep Shastri in CERSSE Election Tracker Issue No. 5. I am attaching the file with the changes

[constituency_region_info_Karnataka_new.zip](https://github.com/tcpd/tcpd-data/files/1934168/constituency_region_info_Karnataka_new.zip)

**Comment by mohitkharb** [comment]
updated in gitlist files
