### ISSUE TITLE
Goa Assembly #4 AC#40 bypoll #1 is wrong

### ISSUE THREAD

**Issue by hangal** [tcpd/tcpd-data#28]
![image](https://user-images.githubusercontent.com/1018175/42654351-ed58b20c-8635-11e8-89ed-a8369b3f0cce.png)

@mohitkharb pls check how this happened.
Did ECI have position 1 and 2? Or did we insert it?
can we add consistency checks nightly to ensure that a lower-numbered position always has higher-numbered votes?

**Comment by mohitkharb** [comment]
We had serial numbers in place of positions for a few bypolls, updated in git commit 7c510ff1384e5f0f8c7
