### ISSUE TITLE
Incorrect merges

### ISSUE THREAD

**Issue by hangal** [tcpd/tcpd-data#44]
The following table should be empty, but isn't:
(same pid appearing multiple times in the same contest)

library(data.table)
GE = fread('~/tcpd_data/GE/Data/derived/candidates_electoral_info.csv')
x = GE[, .N, .(pid,Assembly_No,Poll_No,State_Name, Constituency_No)]
x[N>1]

          pid Assembly_No Poll_No       State_Name Constituency_No N
 1: GEAP53863          11       0   Andhra_Pradesh              31 2
 2: GEAP51141          11       0   Andhra_Pradesh              41 2
 3: GEAP51276          11       0   Andhra_Pradesh              41 2
 4: GEAP51135          11       0   Andhra_Pradesh              41 2
 5: GEAP51008          11       0   Andhra_Pradesh              41 2
 6: GEAP50968          11       0   Andhra_Pradesh              41 2
 7: GEAP51028          11       0   Andhra_Pradesh              41 2
 8: GEAS42738          11       0            Assam               1 2
 9: GEBR16413          12       0            Bihar              12 2
10:  GECG2271          16       0     Chhattisgarh               4 2
11:  GEGJ2711          15       0          Gujarat               5 2
12:  GEGJ3013          15       0          Gujarat              14 2
13: GEGJ47252          14       0          Gujarat              21 2
14:  GEHP3814          16       0 Himachal_Pradesh               3 2
15:  GEHP3841          16       0 Himachal_Pradesh               4 2
16: GEKA15580          11       0        Karnataka              15 2
17: GEKA15939          11       0        Karnataka              25 2
18: GEKA16019          11       0        Karnataka              25 2
19:  GEKL5675          16       0           Kerala              13 3
20: GEKL75310          15       0           Kerala               3 2
21:  GEKL5775          15       0           Kerala              18 2
22: GEKL31495          10       0           Kerala              11 2
23: GEKL44806           9       0           Kerala              12 2
24:  GEMP5892          15       0   Madhya_Pradesh               1 2
25:  GEMP6056          15       0   Madhya_Pradesh               6 2
26:  GEMP6158          15       0   Madhya_Pradesh               9 2
27: GEMP45026          10       0   Madhya_Pradesh               7 2
28: GECG31723          10       0   Madhya_Pradesh              16 2
29: GEMP31646           9       0   Madhya_Pradesh               7 2
30: GEMP22498           6       0   Madhya_Pradesh              33 2
31:  GEMH7949          16       0      Maharashtra              40 2
32: GEMH70723          14       0      Maharashtra               3 2
33:  GEPB8835          16       0           Punjab              11 2
34:  GERJ9323          16       0        Rajasthan              13 2
35:  GERJ9180          15       0        Rajasthan               8 2
36:  GETN1332          11       0       Tamil_Nadu              16 2
37: GETN64013          11       0       Tamil_Nadu              21 2
38: GETR39559          10       0          Tripura               1 2
39: GEUP11651          16       0    Uttar_Pradesh              17 2
40: GEUP83299          15       0    Uttar_Pradesh              23 2
41: GEUP12939          15       0    Uttar_Pradesh              59 2
42: GEUP67395          14       0    Uttar_Pradesh              17 2
43: GEUP77695          14       0    Uttar_Pradesh              29 2
44: GEUP72788          14       0    Uttar_Pradesh              78 2
45: GEUP33570          13       0    Uttar_Pradesh              29 2
46: GEUP62489          11       0    Uttar_Pradesh              64 2
47: GEUP62674          11       0    Uttar_Pradesh              68 2
48: GEUP33521           8       0    Uttar_Pradesh              26 2
49: GEUP33613           8       0    Uttar_Pradesh              33 2
50: GEWB29173          14       0      West_Bengal              22 2

after correction, please ensure the above table is empty.

**Comment by mohitkharb** [comment]
updated in git commit aff713c246879c7.
@hangal : can you please check, I ran the script and it showed me no cases like this left.

**Comment by hangal** [comment]
ok, thanks. verified, closing.
