### ISSUE TITLE
Revert changes back to a working version

### ISSUE THREAD

**Issue by hangal** [tcpd/tcpd-data#7]
GE primary data seems to have gotten corrupted.
We need to revert back to a working version.
@sudesh-ashoka 

Please run consistency checks before checking in.

**Comment by sudesh-ashoka** [comment]
File is Rolled back to older commit.

**Comment by hangal** [comment]
@sudesh-ashoka pls also put in the commit id that fixes the ECO.
in this case it is 883f793ba9111776834591eaac32d50c16578528
this ECO removes the ga_no column, so it will be re-introduced.
