### ISSUE TITLE
Please normalize state names

### ISSUE THREAD

**Issue by hangal** [tcpd/tcpd-data#8]
In Candidate and constituency files using StateNameNormalized.csv

Ensure that all rows have state names that are standardized.
Standardized state name => that name is in the right column of StateNameNormalized.csv.
This should become an invariant.

**Comment by sudesh-ashoka** [comment]
Fixed.

**Comment by hangal** [comment]
Seems ok. Mohit, pls run consistency checks to ensure that ALL state names in all primary files (including defunct ones such as Mysore, Madras and "Goa, Daman and Diu" are in StateNameNormalized.csv in the second column (modulo case).
